// <auto-generated />
using Fiszki.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fiszki.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fiszki.Models.Fiszkii", b =>
                {
                    b.Property<int>("id_fiszki")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("Kategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa_fiszki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Przedmiot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Zrobione")
                        .HasColumnType("bit");

                    b.HasKey("id_fiszki");

                    b.ToTable("Fiszkiii");

                    b.HasData(
                        new
                        {
                            id_fiszki = 5,
                            Done = false,
                            Kategoria = "ijgfd",
                            Nazwa_fiszki = "sdfghj",
                            Opis = "sdfghjkljfdsfghjkmhg",
                            Przedmiot = "hjgytfrds",
                            Zrobione = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
